name: 1.1 Create Workflow # Node.js CI

on:
  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - 'README.md'
  # pull_request:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - 'README.md'
  workflow_dispatch:  

jobs:
  build:
    # if: "!contains(github.event.head_commit.message, 'README.md')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    name: Node.js ${{ matrix.node-version }} Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Check out the source code from the repository.

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Use npm caching for faster dependency installs.

      - name: Install dependencies
        run: npm ci    # Perform a clean install of Node.js dependencies.

      - name: Run tests
        run: npm test    # Run tests using the specified Node.js version.
