# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI # Workflow name

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:  # Trigger
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '22.x'                # set this to the node version to use
  
jobs:
  Build-And-Test:   # Job name - build

    runs-on: ubuntu-latest  # Target Runner Type 

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:  # List of steps to be executed within the job
    - name: Checkout Code 
      uses: actions/checkout@v4

    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: Check out repository code
      uses: actions/checkout@v4
    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
    - run: echo "🖥️ The workflow is now ready to test your code on the runner."
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - run: echo "🍏 This job's status is ${{ job.status }}."      

    - name: Execute the Command
      run: echo "Hello, GitHub Workflow!" 

    - name: Print repository name
      run: echo "The repository is ${{ github.repository }}"      

    - name: Check Event Name
      run: echo "This workflow was triggered by a ${{ github.event_name }} event."
      
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: node -v
    
    - run: npm ci
    
    - run: npm run build --if-present
    
    - run: npm test

    - name: Zip artifact for deployment
      run: zip release.zip ./* -r

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: release.zip

  Deploy-To-Azure:
    runs-on: ubuntu-latest
    needs: Build-And-Test
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: unzip artifact for deployment
        run: unzip release.zip          
        
      # - name: 'Deploy to Azure Web App'
      #   id: deploy-to-webapp
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #     slot-name: 'production'
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
